### ISSUE TITLE
The Accountability Office

### ISSUE THREAD

**Issue by dluman** [NaNoGenMo/2017#10]
I work in web operations at a [LARGE GOVERNMENT ACCOUNTABILITY OFFICE]. Often, what we do revolves around companies and contractors appealing contracting decisions made by various arms of the federal government. Typically, these are service or manufacturing contracts whose arbitration falls to the teams of lawyers here. This seemed somewhat benign and mundane to me until I thought about what I was going to do this NaNoGenMo.

Science fiction loves the idea of the "corporation." Big, bad, evil corporations exist in most sci-fi worlds. While their degree of control over economies and daily life varies from world-to-world, I got to thinking about ways to use corporate constructs and the form of the legal arbitration documents I process (they're public documents) as a kind of storytelling. Similar in spirit to the Marvel comic, [Wrecking Crew](https://en.wikipedia.org/wiki/Wrecking_Crew_(comics)), I am injecting a little joy into the hapless legalese that I uncomprehendingly stare at every day, the storyline of what happens behind the scenes in a "Freaknomics"-ish kind-of way.

"Blade Runner" takes place in November of 2019. I seem to like doing things that revolve around the experiential time period of NaNoGenMo, so one possibility I'm considering is acting from a world government perspective, creating a book of various bid protest successes and failures of corporations in that world. I could also take it to a fictitious place and create dummy corps. (probably what I'll do), but the genesis of the project lies in thinking about mapping the "Blade Runner"  universe onto this one -- one in which Tyrell Corp. and others bid (sometimes successfully, sometimes not) for government contracts to manufacture or service "future stuff."

These would take the form of the decisions that some faceless "accountability office" issues, using the form and text from real-world documents that have been processed during the month of November for as far back as I can go. Since these documents are public (some redacted, others not) the corpus is accessible and usable (even if I need to do a little scraping or batch document processing). This seems ideal for Markov chaining or neural networking, but the final method is somewhat undecided at this time.

I'll post my various updates here, though I'll probably be submitting other projects.

**Comment by enkiv2** [comment]
I love the idea of an epistolary novel constructed from legal filings!

**Comment by dluman** [comment]
Going to have to put this one on hold until next year; I may mess with it in 2018 independent of NGM, but I'm calling it for rain/time crunch.
