### ISSUE TITLE
Omg, I'm in.

### ISSUE THREAD

**Issue by joshuadanpeterson** [NaNoGenMo/2017#44]
I have a few vague ideas about what to do, but only because I just heard about this five minutes ago on [Twitter](https://twitter.com/molly0x57/status/925497998569885697). I've been wanting to play around with machine learning and text summarization (robot reporting), and I've also been wanting to do #NaNoWriMo, and so I think that this will be a good combination of the two. I'll update this issue later as my idea develops.

**Comment by joshuadanpeterson** [comment]
Last night I forked the repository to work on the project on Github. Today, I added the beginning of a new README for my project, and also started a dev diary.

**Comment by ikarth** [comment]
I don't remember too much being done with text summarization in NaNoGenMo before, and it strikes me that it's a rich vein to mine for techniques.

**Comment by joshuadanpeterson** [comment]
Awesome, thank you. I'm excited to be one of the first to try it out then.

**Comment by joshuadanpeterson** [comment]
Well, since I didn't have much time this month to work on figuring how to do this from scratch, I didn't make it happen this year. That being said, I did experiment and find some new techniques for myself as a writer, so in that sense, this was a success. Looking forward to figuring this out and trying again next NaNoGenMo.

**Comment by hugovk** [comment]
Good stuff, welcome back next year!
