### ISSUE TITLE
Question about the rules

### ISSUE THREAD

**Issue by cpressey** [NaNoGenMo/2017#71]
The README says:

"If you already have some inkling of the kind of project you'll be doing, please title your issue accordingly."

(in italics, presumably for emphasis.)

My question is this.  If one has some concrete idea in mind for their project, but does not wish to reveal it immediately via their issue title, is one then disqualified from participating in NaNoGenMo?

**Comment by enkiv2** [comment]
Only if they also are pleased to title their issue accordingly. If they are displeased to title their issue accordingly, then it doesn't matter either way.

**Comment by hugovk** [comment]
They won't be disqualified. 

> The only rule is that you share at least one novel and also your source code at the end.

**Comment by cpressey** [comment]
OK.  Thanks for answering.
