### ISSUE TITLE
Intending to Play - Game Style Generated Narrative

### ISSUE THREAD

**Issue by chipmonkey** [NaNoGenMo/2017#73]
Ok, last year didn't go so well.  New approach.  Writing a proc-gen style video game (with a mode where the computer just plays randomly) and a narrative component describes what is happening.  Thus: generated book.  I've seen this approach before... simpler than my last effort.  :-)  This is really a cross-job with http://www.procjam.com/, so.... two birds with one stone, yes?

**Comment by ikarth** [comment]
Sounds like a good plan. Looking forward to seeing the results!

**Comment by chipmonkey** [comment]
*sigh* It did not go well... I may have to put this sort of thing off until after grad school.  Good luck everyone else!
