### ISSUE TITLE
Intent to participate

### ISSUE THREAD

**Issue by sganondorf** [NaNoGenMo/2017#76]
No idea with what yet though 🙃

**Comment by sganondorf** [comment]
I've decided to start working with improv because of it's similarity with tracery (something I used making [a basic twitter bot](https://twitter.com/neatgamesbot) with cheapbots done quick) as well as the fact that it's really well documented.

The repo I'll be working out of is [here](https://github.com/sganondorf/nanogenmo-2017), I'm going to first start out by working through [this excellent procjam tutorial.](http://www.procjam.com/tutorials/improv/)

Still not completely decided on _what_ form this project will take but I'm looking forward to learning a bit about what improv can do and then fleshing out my concept a bit more through this issue.

**Comment by sganondorf** [comment]
I learned a thing or two about improv and even generated a paragraph or two, but unfortunately life events (and maybe binge watching [Mindhunter](http://www.imdb.com/title/tt5290382/) one weekend) prevented me from making the deadline this year which is a shame.

**Comment by hugovk** [comment]
Welcome back next year!
